// Generated by ReScript, PLEASE EDIT WITH CARE


var x = {
  contents: 9
};

x.contents = x.contents + 1 | 0;

var y = {
  contents: 7
};

function okay(x) {
  return x.contents;
}

function Main(Props) {
  return 1;
}

function Main$make1(Props) {
  return 1;
}

function myFun(x, y) {
  var doubleX = x.contents + x.contents | 0;
  var doubleY = y.contents + y.contents | 0;
  return doubleX + doubleY | 0;
}

console.log("consolelog");

var payloadResults = [
  {
    TAG: /* Ok */0,
    _0: {
      data: "hi"
    }
  },
  {
    TAG: /* Ok */0,
    _0: {
      data: "bye"
    }
  },
  {
    TAG: /* Error */1,
    _0: "Something wrong happened!"
  }
];

var defaultId = 10;

var str = "hello world";

var make = Main;

var make1 = Main$make1;

var score = 10;

var a = [
  10,
  20,
  20
];

var buddy = [
  10,
  20,
  20
];

export {
  defaultId ,
  x ,
  y ,
  str ,
  okay ,
  make ,
  make1 ,
  myFun ,
  score ,
  a ,
  buddy ,
  payloadResults ,
  
}
/*  Not a pure module */
