// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";

function Test(Props) {
  var match = React.useState(function () {
        return 0;
      });
  var setCount = match[1];
  var onClickInc = function (_evt) {
    return Curry._1(setCount, (function (prev) {
                  return prev + 1 | 0;
                }));
  };
  var onClickDec = function (_evt) {
    return Curry._1(setCount, (function (prev) {
                  return prev - 1 | 0;
                }));
  };
  var msg = "through rescript " + String(match[0]);
  return React.createElement("div", undefined, React.createElement("button", {
                  className: "counter-button btn--primary",
                  onClick: onClickDec
                }, "-"), React.createElement("span", {
                  className: "counter-button"
                }, msg), React.createElement("button", {
                  className: "counter-button btn--primary",
                  onClick: onClickInc
                }, "+"));
}

var make = Test;

export {
  make ,
  
}
/* react Not a pure module */
